In [1]:
import pandas as pd
import os

path = r'C:\Users\Shimaa\Desktop\Huawei_Internship_16_Sep\Datasets\ICUDatasetProcessed'

file_list = os.listdir(path)

file_list

['Attack.csv', 'environmentMonitoring.csv', 'patientMonitoring.csv']

In [2]:
df1 = pd.read_csv(os.path.join(path, file_list[0]))
df1.head()

C:\Users\Shimaa\AppData\Local\Temp\ipykernel_12840\1947260423.py:1: DtypeWarning: Columns (26,28,35) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv(os.path.join(path, file_list[0]))

,frame.time_delta,frame.time_relative,frame.len,ip.src,ip.dst,tcp.srcport,tcp.dstport,tcp.flags,tcp.time_delta,tcp.len,...,mqtt.qos,mqtt.retain,mqtt.topic,mqtt.topic_len,mqtt.ver,mqtt.willmsg_len,ip.proto,ip.ttl,class,label
0,0.000000,0.000000,74,10.16.120.44,10.16.120.72,56808,1883,0x00000002,0.000000,0,...,0.0,0.0,0.0,0.0,0.0,0.0,6,64,Attack,1
1,0.000052,0.000052,74,10.16.120.72,10.16.120.44,1883,56808,0x00000012,0.000052,0,...,0.0,0.0,0.0,0.0,0.0,0.0,6,64,Attack,1
2,0.000008,0.000060,74,10.16.120.44,10.16.120.72,56810,1883,0x00000002,0.000000,0,...,0.0,0.0,0.0,0.0,0.0,0.0,6,64,Attack,1
3,0.000012,0.000072,74,10.16.120.72,10.16.120.44,1883,56810,0x00000012,0.000012,0,...,0.0,0.0,0.0,0.0,0.0,0.0,6,64,Attack,1
4,0.000003,0.000075,74,10.16.120.44,10.16.120.72,56812,1883,0x00000002,0.000000,0,...,0.0,0.0,0.0,0.0,0.0,0.0,6,64,Attack,1

In [3]:
df2 = pd.read_csv(os.path.join(path, file_list[1]))
df2.head()

,frame.time_delta,frame.time_relative,frame.len,ip.src,ip.dst,tcp.srcport,tcp.dstport,tcp.flags,tcp.time_delta,tcp.len,...,mqtt.qos,mqtt.retain,mqtt.topic,mqtt.topic_len,mqtt.ver,mqtt.willmsg_len,ip.proto,ip.ttl,class,label
0,0.000000,0.000000,105,10.5.126.151,10.5.126.84,40629,1883,0x00000018,0.000000,37,...,0.0,0.0,0,0.0,4.0,0.0,6,64,environmentMonitoring,0
1,0.000053,0.000053,72,10.5.126.84,10.5.126.151,1883,40629,0x00000018,0.000053,4,...,0.0,0.0,0,0.0,0.0,0.0,6,64,environmentMonitoring,0
2,0.000043,0.000096,105,10.5.126.153,10.5.126.84,45639,1883,0x00000018,0.000000,37,...,0.0,0.0,0,0.0,4.0,0.0,6,64,environmentMonitoring,0
3,0.000020,0.000116,72,10.5.126.84,10.5.126.153,1883,45639,0x00000018,0.000020,4,...,0.0,0.0,0,0.0,0.0,0.0,6,64,environmentMonitoring,0
4,0.000016,0.000132,105,10.5.126.155,10.5.126.84,45093,1883,0x00000018,0.000000,37,...,0.0,0.0,0,0.0,4.0,0.0,6,64,environmentMonitoring,0

In [4]:
df3 = pd.read_csv(os.path.join(path, file_list[2]))
df3.head()

C:\Users\Shimaa\AppData\Local\Temp\ipykernel_12840\3907388685.py:1: DtypeWarning: Columns (26,28,35) have mixed types. Specify dtype option on import or set low_memory=False.
  df3 = pd.read_csv(os.path.join(path, file_list[2]))

,frame.time_delta,frame.time_relative,frame.len,ip.src,ip.dst,tcp.srcport,tcp.dstport,tcp.flags,tcp.time_delta,tcp.len,...,mqtt.qos,mqtt.retain,mqtt.topic,mqtt.topic_len,mqtt.ver,mqtt.willmsg_len,ip.proto,ip.ttl,class,label
0,0.000000,0.000000,105,10.5.126.141,10.5.126.56,35161,1883,0x00000018,0.0,37,...,0.0,0.0,0,0.0,4.0,0.0,6,64,patientMonitoring,0
1,0.000249,0.000249,105,10.5.126.143,10.5.126.56,34237,1883,0x00000018,0.0,37,...,0.0,0.0,0,0.0,4.0,0.0,6,64,patientMonitoring,0
2,0.000037,0.000286,105,10.5.126.145,10.5.126.56,46623,1883,0x00000018,0.0,37,...,0.0,0.0,0,0.0,4.0,0.0,6,64,patientMonitoring,0
3,0.000034,0.000320,105,10.5.126.147,10.5.126.56,45663,1883,0x00000018,0.0,37,...,0.0,0.0,0,0.0,4.0,0.0,6,64,patientMonitoring,0
4,0.000017,0.000337,105,10.5.126.141,10.5.126.56,38901,1883,0x00000018,0.0,37,...,0.0,0.0,0,0.0,4.0,0.0,6,64,patientMonitoring,0

In [5]:
print(f'df1.shape: {df1.shape}')
print(f'df2.shape: {df2.shape}')
print(f'df3.shape: {df3.shape}')

df1.shape: (80126, 52)
df2.shape: (31758, 52)
df3.shape: (76810, 52)

In [6]:
# Check if all DataFrames have the same columns
if (df1.columns.equals(df2.columns)) and (df2.columns.equals(df3.columns)):
    print("All three DataFrames have identical columns.")
else:
    print("The DataFrames have different columns.")

All three DataFrames have identical columns.

- axis=0 means that you are concatenating the DataFrames vertically (i.e., stacking them on top of each other). This combines the rows of the DataFrames, adding the rows from df2 below the rows from df1.
- we use -> ignore_index=True

- axis=1 would mean that you are concatenating the DataFrames horizontally (i.e., side by side). This combines the columns of the DataFrames, adding the columns from df2 next to the columns from df1.
- we use -> ignore_index=False

In [7]:
merged_df = pd.concat([df1, df2, df3], axis=0, ignore_index=True)
merged_df.shape

(188694, 52)

In [8]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188694 entries, 0 to 188693
Data columns (total 52 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   frame.time_delta       188694 non-null  float64
 1   frame.time_relative    188694 non-null  float64
 2   frame.len              188694 non-null  int64
 3   ip.src                 188694 non-null  object
 4   ip.dst                 188694 non-null  object
 5   tcp.srcport            188694 non-null  int64
 6   tcp.dstport            188694 non-null  int64
 7   tcp.flags              188694 non-null  object
 8   tcp.time_delta         188694 non-null  float64
 9   tcp.len                188694 non-null  int64
 10  tcp.ack                188694 non-null  int64
 11  tcp.connection.fin     188694 non-null  float64
 12  tcp.connection.rst     188694 non-null  float64
 13  tcp.connection.sack    188694 non-null  float64
 14  tcp.connection.syn     188694 non-null  float64
 15  tcp.flags.ack          188694 non-null  int64
 16  tcp.flags.fin          188694 non-null  int64
 17  tcp.flags.push         188694 non-null  int64
 18  tcp.flags.reset        188694 non-null  int64
 19  tcp.flags.syn          188694 non-null  int64
 20  tcp.flags.urg          188694 non-null  int64
 21  tcp.hdr_len            188694 non-null  int64
 22  tcp.payload            188694 non-null  object
 23  tcp.pdu.size           188694 non-null  float64
 24  tcp.window_size_value  188694 non-null  int64
 25  tcp.checksum           188694 non-null  object
 26  mqtt.clientid          188694 non-null  object
 27  mqtt.clientid_len      188694 non-null  float64
 28  mqtt.conack.flags      188694 non-null  object
 29  mqtt.conack.val        188694 non-null  float64
 30  mqtt.conflag.passwd    188694 non-null  float64
 31  mqtt.conflag.qos       188694 non-null  float64
 32  mqtt.conflag.reserved  188694 non-null  float64
 33  mqtt.conflag.retain    188694 non-null  float64
 34  mqtt.conflag.willflag  188694 non-null  float64
 35  mqtt.conflags          188694 non-null  object
 36  mqtt.dupflag           188694 non-null  float64
 37  mqtt.hdrflags          188694 non-null  object
 38  mqtt.kalive            188694 non-null  float64
 39  mqtt.len               188694 non-null  float64
 40  mqtt.msg               188694 non-null  object
 41  mqtt.msgtype           188694 non-null  float64
 42  mqtt.qos               188694 non-null  float64
 43  mqtt.retain            188694 non-null  float64
 44  mqtt.topic             188694 non-null  object
 45  mqtt.topic_len         188694 non-null  float64
 46  mqtt.ver               188694 non-null  float64
 47  mqtt.willmsg_len       188694 non-null  float64
 48  ip.proto               188694 non-null  int64
 49  ip.ttl                 188694 non-null  int64
 50  class                  188694 non-null  object
 51  label                  188694 non-null  int64
dtypes: float64(24), int64(16), object(12)
memory usage: 74.9+ MB

In [9]:
num_df = merged_df.select_dtypes(include=['number'])
nan_df = merged_df.select_dtypes(exclude=['number'])

print(f'len(num_df.columns): {len(num_df.columns)}\nnum_df.columns\n{num_df.columns}')
print(f'len(nan_df.columns): {len(nan_df.columns)}\nnan_df.columns\n{nan_df.columns}')

len(num_df.columns): 40
num_df.columns
Index(['frame.time_delta', 'frame.time_relative', 'frame.len', 'tcp.srcport',
       'tcp.dstport', 'tcp.time_delta', 'tcp.len', 'tcp.ack',
       'tcp.connection.fin', 'tcp.connection.rst', 'tcp.connection.sack',
       'tcp.connection.syn', 'tcp.flags.ack', 'tcp.flags.fin',
       'tcp.flags.push', 'tcp.flags.reset', 'tcp.flags.syn', 'tcp.flags.urg',
       'tcp.hdr_len', 'tcp.pdu.size', 'tcp.window_size_value',
       'mqtt.clientid_len', 'mqtt.conack.val', 'mqtt.conflag.passwd',
       'mqtt.conflag.qos', 'mqtt.conflag.reserved', 'mqtt.conflag.retain',
       'mqtt.conflag.willflag', 'mqtt.dupflag', 'mqtt.kalive', 'mqtt.len',
       'mqtt.msgtype', 'mqtt.qos', 'mqtt.retain', 'mqtt.topic_len', 'mqtt.ver',
       'mqtt.willmsg_len', 'ip.proto', 'ip.ttl', 'label'],
      dtype='object')
len(nan_df.columns): 12
nan_df.columns
Index(['ip.src', 'ip.dst', 'tcp.flags', 'tcp.payload', 'tcp.checksum',
       'mqtt.clientid', 'mqtt.conack.flags', 'mqtt.conflags', 'mqtt.hdrflags',
       'mqtt.msg', 'mqtt.topic', 'class'],
      dtype='object')

In [10]:
from sklearn.preprocessing import LabelEncoder

for col in nan_df.columns:
    nan_df[col] = nan_df[col].astype(str) # Convert all values in the column to string to ensure uniformity
    nan_df[col] = LabelEncoder().fit_transform(nan_df[col])

merged_df = pd.concat([num_df, nan_df], axis=1, ignore_index=False)

merged_df

,frame.time_delta,frame.time_relative,frame.len,tcp.srcport,tcp.dstport,tcp.time_delta,tcp.len,tcp.ack,tcp.connection.fin,tcp.connection.rst,...,tcp.flags,tcp.payload,tcp.checksum,mqtt.clientid,mqtt.conack.flags,mqtt.conflags,mqtt.hdrflags,mqtt.msg,mqtt.topic,class
0,0.000000,0.000000,74,56808,1883,0.000000,0,0,0.0,0.0,...,0,0,27801,2,0,0,0,62,50,0
1,0.000052,0.000052,74,1883,56808,0.000052,0,1,0.0,0.0,...,4,0,27588,2,0,0,0,62,50,0
2,0.000008,0.000060,74,56810,1883,0.000000,0,0,0.0,0.0,...,0,0,33722,2,0,0,0,62,50,0
3,0.000012,0.000072,74,1883,56810,0.000012,0,1,0.0,0.0,...,4,0,2626,2,0,0,0,62,50,0
4,0.000003,0.000075,74,56812,1883,0.000000,0,0,0.0,0.0,...,0,0,44444,2,0,0,0,62,50,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188689,0.000196,6611.037621,78,44993,1883,1.989358,10,225,0.0,0.0,...,6,592,3098,2,0,0,3,1861,55,2
188690,0.000172,6611.037793,77,38323,1883,1.989338,9,225,0.0,0.0,...,6,529,3080,2,0,0,3,6810,56,2
188691,0.000126,6611.037919,77,41889,1883,1.989337,9,225,0.0,0.0,...,6,522,3080,2,0,0,3,6499,56,2
188692,0.000146,6611.038065,77,35965,1883,1.989211,9,225,0.0,0.0,...,6,520,3099,2,0,0,3,6397,56,2
188693,0.000147,6611.038212,77,33251,1883,1.989194,9,225,0.0,0.0,...,6,528,3099,2,0,0,3,6762,56,2

In [11]:
print(f'len(merged_df.columns): {len(merged_df.columns)}')

non_feats_col = []
for col in merged_df.columns:
    if len(merged_df[col].unique()) == 1:
        non_feats_col.append(col)

merged_df = merged_df.drop(labels=non_feats_col, axis=1, inplace=False)

print(f'len(non_feats_col): {len(non_feats_col)}')
print(f'len(merged_df.columns): {len(merged_df.columns)}')

len(merged_df.columns): 52
len(non_feats_col): 9
len(merged_df.columns): 43

In [12]:
from sklearn.preprocessing import MinMaxScaler

X = merged_df.iloc[:, :-1].values
y = merged_df.iloc[:, -1].values

X = MinMaxScaler().fit_transform(X)

print(f'X.shape: {X.shape}')
print(f'y.shape: {y.shape}')

X.shape: (188694, 42)
y.shape: (188694,)

In [13]:
from sklearn.feature_selection import SelectKBest, chi2

X = SelectKBest(chi2, k=30).fit_transform(X, y)
X.shape

(188694, 30)

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score

model = LogisticRegression()
model_result = model.fit(X_train, y_train)

y_pred = model_result.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
acc = accuracy_score(y_test, y_pred)

print(f'confusion_matrix\n{cm}\n')
print(f'accuracy_score: {acc}')

confusion_matrix
[[15915     0     0]
 [    0  5089  1278]
 [    0   339 15118]]

accuracy_score: 0.9571530777180105